### ISSUE TITLE
add to fileSec

### ISSUE THREAD

**Issue by witzigs** [je4/gocfl#51]
* fileSec braucht noch ID
* Schemas sollten in eine eigen fileGrp mit  USE = Schemas
* falls wir Documenation haben, sollten die files auch in eine eigen fileGrp mit USE = Documentation
* file braucht noch SIZE und CREATED

**Comment by je4** [comment]
was machen wir, wenn durch die Deduplizierung ein File in mehreren bereichen auftaucht?

**Comment by je4** [comment]
central element of mets is external file now.
