### ISSUE TITLE
add to structMap

### ISSUE THREAD

**Issue by je4** [je4/gocfl#52]
structMap fehlt ein div "metadata"

**Comment by witzigs** [comment]
gemäss CSIP ist die Definition für structMap/div/div[@ LABEL = metadata:
The metadata referenced in the administrative and/or descriptive
metadata section is described in the structural map with one sub
division. When the transfer consists of only administrative and/or
descriptive metadata this is the only sub division that occurs.

**Comment by je4** [comment]
metadata in structMap
