### ISSUE TITLE
file name of thumbnails too long

### ISSUE THREAD

**Issue by kathrin77** [je4/gocfl#72]
hi @je4 
if thumbnails are generated, the filenames are too long for Windows environment and the zipped archives cannot be unzipped. 
Example from zhb:
`.\dlza_test\zhb_sosa_emanus_10_7891_e-manuscripta-23309.zip\zhb_sosa_emanus_10_7891_e-manuscripta-23309\extensions\NNNN-thumbnail\data\0\2\0266d88ba25c1c61f24541e135f1f64e0be3f475854fe0ea153116b993b2b0fcc128b23ab07c1d5931c902c6486ceb1eea713a59ac2a44b7be1494de844f9dbf.png`

File length to open/unzip files in Windows is 256 characters. The thumbnail names alone are already 128 characters. Can these be shortened?
BR Kathrin/ZHB

**Comment by je4** [comment]
object extension config of NNNN-thumbnail has new boolean field  shortFilename.
setting this field to true will create an SHA-1 checksum from the manifest digest as filename, which is shorter, but risk of collission is slightly higher.
